routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('employees', 'EmployeeController');
Route::get('/', function () {
    return redirect()->route('employees.create');
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('profile', 'ProfileController');

});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;
    protected $fillable=[
        'blood_group','cnic_address','cnic','allergies','emergency_name','emergency_relationship','emergency_contact','emergency_email','user_id','salary_slip_pic','cnic_pic'
    ];

    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\BankDetail;
use App\Employee;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->role_id != 1) {
            return redirect()->back();
        }
        $employees = Employee::paginate(25);
        return view('admin.employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (auth()->user() != null) {
            if (auth()->user()->role->name == 'admin') {
                return view('admin.employees.create');
            }
        }
        return view('frontend.forms.registration');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'address' => 'required',
            'contact' => 'required|numeric|digits:11',
            'first_name' => 'required',
            'last_name' => 'required',
            'cnic_address' => 'required',
            'email' => 'unique:users,email',
            'cnic' => 'required|numeric|digits:13',
            'account_number' => 'nullable|numeric|digits_between:14,16',
            'emergency_name' => 'required',
            'emergency_relationship' => 'required',
            'emergency_contact' => 'required|numeric|digits:11',
            'profile_pic' => 'required|max:6000|mimes:img,jpg,jpeg,png',
            'cnic_pic' => 'required|max:6000|mimes:img,jpg,jpeg,png',
            'salary_slip_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
        ]);

        $salary_slip_pic = null;
        $is_approved = 0;

        if (optional(auth()->user())->role_id == 1) {
            $is_approved = $request->is_approved;
        }
        $profile_pic = $request->file('profile_pic');
        $profile_pic = $this->uploadFile($profile_pic, 'documents');

        $cnic_pic = $request->file('cnic_pic');
        $cnic_pic = $this->uploadFile($cnic_pic, 'documents');

        if ($request->hasFile('salary_slip_pic')) {
            $salary_slip_pic = $request->file('salary_slip_pic');
            $salary_slip_pic = $this->uploadFile($salary_slip_pic, 'documents');
        }

        \DB::transaction(function () use ($salary_slip_pic, $profile_pic, $cnic_pic,$is_approved, $request) {
            $user = User::create($request->except('profile_pic', 'password', 'is_approved') + ['is_approved'=>$is_approved,'profile_pic' => $profile_pic, 'password' => Hash::make($request->password)]);
            Employee::create($request->except('user_id', 'cnic_pic', 'salary_slip_pic') + ['user_id' => $user->id, 'cnic_pic' => $cnic_pic, 'salary_slip_pic' => $salary_slip_pic]);
            BankDetail::create($request->except('user_id') + ['user_id' => $user->id]);
        });
        return redirect()->back()->with(['message' => 'Employee Created Successfully']);
    }

    public function uploadFile($file, $path)
    {
        $destinationPath = $path;
        $originalFile = $file->getClientOriginalName();
        $filename1 = time() . '-' . $originalFile;
        $filename2 = $filename1;
        $fileextension = $file->getClientOriginalExtension();
        $filesize = $file->getSize();
        $file->move($destinationPath, $filename1);
        return $filename2;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (auth()->user()->role_id != 1) {
            return redirect()->back();
        }
        $this->validate($request, [
            'address' => 'required',
            'contact' => 'required|numeric|digits:11',
            'first_name' => 'required',
            'last_name' => 'required',
            'cnic_address' => 'required',
            'email' => 'required',
            'cnic' => 'required|numeric|digits:13',
            'account_number' => 'nullable|numeric|digits_between:14,16',
            'emergency_name' => 'required',
            'emergency_relationship' => 'required',
            'emergency_contact' => 'required|numeric|digits:11',
            'profile_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
            'cnic_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
            'salary_slip_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
        ]);

        $user = User::find($id);
        $salary_slip_pic = $user->employee->salary_slip_pic;
        $profile_pic = $user->profile_pic;
        $cnic_pic = $user->employee->cnic_pic;
        $is_approved = 0;

        if (optional(auth()->user())->role_id == 1) {
            $is_approved = $request->is_approved;
        }

        if ($request->hasFile('profile_pic')) {
            $profile_pic = $request->file('profile_pic');
            $profile_pic = $this->uploadFile($profile_pic, 'documents');
        }

        if ($request->hasFile('cnic_pic')) {
            $cnic_pic = $request->file('cnic_pic');
            $cnic_pic = $this->uploadFile($cnic_pic, 'documents');
        }

        if ($request->hasFile('salary_slip_pic')) {
            $salary_slip_pic = $request->file('salary_slip_pic');
            $salary_slip_pic = $this->uploadFile($salary_slip_pic, 'documents');
        }

        $employee = Employee::where('user_id', $id)->first();
        $bank_detail = BankDetail::where('user_id', $id)->first();

        \DB::transaction(function () use ($salary_slip_pic, $profile_pic, $cnic_pic, $request, $employee, $bank_detail, $user, $id, $is_approved) {

            if ($request->password != null) {
                $user->update($request->except('profile_pic', 'is_approved') + ['is_approved'=>$is_approved,'profile_pic' => $profile_pic, 'password' => Hash::make($request->password)]);
            } else {
                $user->update($request->except('profile_pic', 'password') + ['profile_pic' => $profile_pic]);
            }
            Employee::find($employee->id)->update($request->except('user_id', 'cnic_pic', 'salary_slip_pic') + ['user_id' => $id, 'cnic_pic' => $cnic_pic, 'salary_slip_pic' => $salary_slip_pic]);
            BankDetail::find($bank_detail->id)->update($request->except('user_id') + ['user_id' => $id]);

        });
        return redirect()->back()->with(['message' => 'created']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (auth()->user()->role_id != 1) {
            return redirect()->back();
        }
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts.app')
@section('content')
    <br>
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Personal Details</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <form method="post" action="{{ route('users.store') }}" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-sm-6">
                        <!-- text input -->
                        <div class="form-group">
                            <label>First Name</label>
                            <input name="first_name" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Last Name</label>
                            <input name="last_name" type="text" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <!-- text input -->
                        <div class="form-group">
                            <label>Email</label>
                            <input name="email" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Password</label>
                            <input name="password" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <!-- textarea -->
                        <div class="form-group">
                            <label>Contact</label>
                            <input name="contact" type="number" class="form-control">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <!-- textarea -->
                        <div class="form-group">
                            <label>Profile Picture</label>
                            <input type="file" accept="image/*" class="form-control" name="profile_picture">
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Address</label>
                            <textarea name="address" class="form-control" rows="2"></textarea>
                        </div>
                    </div>



                </div>

                <div class="text-right">
                    <input type="submit" value="Submit" class="btn btn-primary">
                </div>
            </form>
        </div>
        <!-- /.card-body -->
    </div>



    @if (Session::has('message'))
        <script>
            $(document).ready(function() {
                Toast.fire({
                    icon: 'success',
                    title: 'User Created Successfully'
                })
            });
        </script>
    @endif

@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.app')
@section('content')
    <style>


    </style>

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="heading col-sm-6">
                    <h1>employees</h1>
                </div>
                <div class="offset-sm-4  col-sm-2">
                    <h1 class="float-sm-right"><span
                        style="background-image: linear-gradient(121deg,black  1%, white 300%);
                        color: white;"
                            class="badge badge-pill">{{ $employees->total() }}</span></h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card searcharea">
                    <div class="align-right">
                    </div>
                    <div class="card-header">
                        <br>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <form action="{{ route('employees.index') }}" style="display: flex;">
                                    <div class="input-group border rounded-pill ">
                                        <input name="keyword" type="search" placeholder="Search"
                                            aria-describedby="button-addon3" class="form-control bg-none border-0">
                                        <div class="input-group-append border-0">
                                            <button id="button-addon3" type="submit" class="btn btn-link text-blue"><i
                                                    class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>

                                <a href="{{ route('employees.create') }}"><button type="button"
                                        class="btn btn-primary rounded-pill rounded-bill">Add
                                        Employee</button></a>
                            </div>
                        </div>

                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap thb">
                            <thead class="table-dark">
                                <tr>
                                    <th>#</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th>CNIC</th>
                                    <th>Blood Group</th>
                                    <th>Emergency Name</th>
                                    <th>Emergency Number</th>
                                    <th>Bank Details</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($employees as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->user->first_name }}</td>
                                    <td>{{ $item->user->last_name }}</td>
                                    <td>{{ $item->user->email }}</td>
                                    <td>{{ $item->cnic }}</td>
                                    <td>{{ $item->blood_group }}</td>
                                    <td>{{ $item->emergency_name }}</td>
                                    <td>{{ $item->emergency_contact }}</td>

                                    <td><a href="#">View</a></td>
                                    <td>

                                        <a href="{{ route('employees.edit', $item->id) }}" class="float-left"><i
                                                class="fas fa-edit"></i></a>
                                        <form action="{{ route('employees.destroy', $item->id) }}" method="POST">
                                            @method('delete') @csrf <button class="btn btn-link pt-0"><i
                                                    class="fas fa-trash-alt"></i></button> </form>
                                    </td>
                                </tr>
                            @empty
                                <p>No Data Found</p>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="align-right paginationstyle">
                            {{ $employees->links() }}
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->


                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    </div>

@endsection