routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('employees', 'EmployeeController');
Route::get('/', function () {
    return redirect()->route('employees.create');
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('profile', 'ProfileController');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','address','contact','first_name','last_name','profile_pic','is_approved'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function employee(){
        return $this->hasOne(Employee::class,'user_id');
    }

    public function bank(){
        return $this->hasOne(BankDetail::class,'user_id');
    }

    public function role(){
        return $this->belongsTo(Role::class,'role_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\BankDetail;
use App\Employee;
use App\Role;
use App\User;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{


    public function __construct()
    {
        // $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            if (auth()->user()->role_id != 1) {
                return redirect()->back();
            }
            return $next($request);
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(25);
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'address' => 'required',
            'contact' => 'required|numeric|digits:11',
            'first_name' => 'required',
            'last_name' => 'required',
            'cnic_address' => 'required',
            'email' => 'unique:users,email',
            'cnic' => 'required|numeric|digits:13',
            'account_number' => 'numeric|digits_between:14,16',
            'emergency_name' => 'required',
            'emergency_relationship' => 'required',
            'emergency_contact' => 'required|numeric|digits:11',
            'profile_pic' => 'required|max:6000|mimes:img,jpg,jpeg,png',
            'cnic_pic' => 'required|max:6000|mimes:img,jpg,jpeg,png',
            'salary_slip_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
        ]);

        $salary_slip_pic = null;
        $profile_pic = $request->file('profile_pic');
        $profile_pic = $this->uploadFile($profile_pic, 'documents');

        $cnic_pic = $request->file('cnic_pic');
        $cnic_pic = $this->uploadFile($cnic_pic, 'documents');

        if ($request->hasFile('salary_slip_pic')) {
            $salary_slip_pic = $request->file('salary_slip_pic');
            $salary_slip_pic = $this->uploadFile($salary_slip_pic, 'documents');
        }

        \DB::transaction(function () use ($salary_slip_pic, $profile_pic, $cnic_pic, $request) {
            $user = User::create($request->except('profile_pic', 'password') + ['profile_pic' => $profile_pic, 'password' => Hash::make($request->password)]);

            Employee::create($request->except('user_id', 'cnic_pic', 'salary_slip_pic') + ['user_id' => $user->id, 'cnic_pic' => $cnic_pic, 'salary_slip_pic' => $salary_slip_pic]);
            BankDetail::create($request->except('user_id') + ['user_id' => $user->id]);
        });
        return redirect()->back()->with(['message' => 'created']);
    }

    public function uploadFile($file, $path)
    {
        $destinationPath = $path;
        $originalFile = $file->getClientOriginalName();
        $filename1 = time() . '-' . $originalFile;
        $filename2 = $filename1;
        $fileextension = $file->getClientOriginalExtension();
        $filesize = $file->getSize();
        $file->move($destinationPath, $filename1);
        return $filename2;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::all();
        $user = User::find($id);
        return view('admin.users.edit', compact('roles', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (auth()->user()->role_id != 1) {
            return redirect()->back();
        }
        $this->validate($request, [
            'address' => 'required',
            'contact' => 'required|numeric|digits:11',
            'first_name' => 'required',
            'last_name' => 'required',

            'cnic_address' => 'required',
            'email' => 'required',
            'cnic' => 'required|numeric|digits:13',
            'account_number' => 'required|numeric|digits_between:14,16',

            'emergency_name' => 'required',
            'emergency_relationship' => 'required',
            'emergency_contact' => 'required|numeric|digits:11',
            'profile_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
            'cnic_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
            'salary_slip_pic' => 'max:6000|mimes:img,jpg,jpeg,png',
        ]);

        $user = User::find($id);
        $salary_slip_pic = $user->employee->salary_slip_pic;
        $profile_pic = $user->profile_pic;
        $cnic_pic = $user->employee->cnic_pic;

        if ($request->hasFile('profile_pic')) {
            $profile_pic = $request->file('profile_pic');
            $profile_pic = $this->uploadFile($profile_pic, 'documents');
        }

        if ($request->hasFile('cnic_pic')) {
            $cnic_pic = $request->file('cnic_pic');
            $cnic_pic = $this->uploadFile($cnic_pic, 'documents');
        }

        if ($request->hasFile('salary_slip_pic')) {
            $salary_slip_pic = $request->file('salary_slip_pic');
            $salary_slip_pic = $this->uploadFile($salary_slip_pic, 'documents');
        }

        $employee = Employee::where('user_id', $id)->first();
        $bank_detail = BankDetail::where('user_id', $id)->first();

        \DB::transaction(function () use ($salary_slip_pic, $profile_pic, $cnic_pic, $request, $employee, $bank_detail, $user, $id) {

            if ($request->password != null) {
                $user->update($request->except('_token', '_method', 'profile_pic', 'password') + ['profile_pic' => $profile_pic, 'password' => Hash::make($request->password)]);
            } else {
                $user->update($request->except('_token', '_method', 'profile_pic', 'password') + ['profile_pic' => $profile_pic]);
            }
            Employee::find($employee->id)->update($request->except('_token', '_method', 'user_id', 'cnic_pic', 'salary_slip_pic') + ['user_id' => $id, 'cnic_pic' => $cnic_pic, 'salary_slip_pic' => $salary_slip_pic]);
            BankDetail::find($bank_detail->id)->update($request->except('_token', '_method', 'user_id') + ['user_id' => $id]);
        });
        return redirect()->back()->with(['message' => 'created']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::where('id', $id)->delete();
        Employee::where('user_id', $id)->delete();
        BankDetail::where('user_id', $id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('content')
    <br>
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">User Information</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @if ($errors->any())
                {!! implode('', $errors->all('<li class="text-danger">:message</li>')) !!}
            @endif
            <form method="post" action="{{ route('employees.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <!-- text input required -->
                    <div class="col-sm-6">

                        <div class="form-group">
                            <label>Role</label>
                            <select required name="role_id" id="" class="form-control">
                                <option value="" selected disabled>Select</option>
                                @foreach ($roles as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-6">

                        <div class="form-group">
                            <label>Approved</label>
                            <select required name="is_approved" id="" class="form-control">
                                <option value="" selected disabled>Select</option>
                                <option value="1">Approved</option>
                                <option value="0">Non-Approved</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <!-- text input required -->
                        <div class="form-group">
                            <label>First Name</label>
                            <input required name="first_name" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Last Name</label>
                            <input required name="last_name" type="text" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <!-- text input required -->
                        <div class="form-group">
                            <label>Email</label>
                            <input required name="email" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Password</label>
                            <input required name="password" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <!-- textarea -->
                        <div class="form-group">
                            <label>Contact</label>
                            <input required name="contact" type="text" pattern="\d*" minlength="11" maxlength="11" class="form-control">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <!-- textarea -->
                        <div class="form-group">
                            <label>Profile Picture</label>
                            <input required type="file" accept="image/*" class="form-control" name="profile_pic">
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Address</label>
                            <textarea name="address" class="form-control" rows="2"></textarea>
                        </div>
                    </div>



                </div>


        </div>
        <!-- /.card-body -->
    </div>

    {{-- --------------------------------------------------Employee Information------------------------------------------------------------------- --}}

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Personal Details</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">

            <div class="row">
                <div class="col-sm-6">
                    <!-- text input required -->
                    <div class="form-group">
                        <label>Blood Group</label>
                        <input required name="blood_group" type="text" class="form-control">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>CNIC</label>
                        <input required name="cnic" type="text" pattern="\d*" minlength="13" maxlength="13" class="form-control">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <!-- text input required -->
                    <div class="form-group">
                        <label>allergies</label>
                        <input required name="allergies" type="text" class="form-control">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Emergency Name</label>
                        <input required name="emergency_name" type="text" class="form-control">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <!-- textarea -->
                    <div class="form-group">
                        <label>Emergency Contact</label>
                        <input required name="emergency_contact" type="text" pattern="\d*" minlength="11" maxlength="11" class="form-control">
                    </div>
                </div>

                <div class="col-sm-6">
                    <!-- textarea -->
                    <div class="form-group">
                        <label>Emergency Relationship</label>
                        <input required name="emergency_relationship" type="text" class="form-control">
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-sm-6">
                    <div class="form-group">
                        <label>CNIC Address</label>
                        <textarea name="cnic_address" class="form-control" rows="2"></textarea>
                    </div>
                </div>

                {{-- <div class="col-sm-6">
                        <!-- textarea -->
                        <div class="form-group">
                            <label>CNIC Picture</label>
                            <input required type="file" accept="image/*" class="form-control" name="cnic_picture">
                        </div>
                    </div> --}}


            </div>

            <div class="row">

                <div class="col-sm-6">
                    <!-- textarea -->
                    <div class="form-group">
                        <label>Salary Slip Picture</label>
                        <input type="file" accept="image/*" class="form-control" name="salary_slip_pic">
                    </div>
                </div>

                <div class="col-sm-6">
                    <!-- textarea -->
                    <div class="form-group">
                        <label>CNIC Picture</label>
                        <input required type="file" accept="image/*" class="form-control" name="cnic_pic">
                    </div>
                </div>


            </div>


        </div>
        <!-- /.card-body -->
    </div>


    {{-- --------------------------------------------------Bank Information------------------------------------------------------------------- --}}

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Bank Details</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">

            <div class="row">
                <div class="col-sm-6">
                    <!-- text input required -->
                    <div class="form-group">
                        <label>Bank Name</label>
                        <input required name="bank_name" type="text" class="form-control">
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-6">
                    <!-- text input required -->
                    <div class="form-group">
                        <label>Account Title</label>
                        <input required name="account_title" type="text" class="form-control">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Account Number</label>
                        <input required name="account_number" type="text" pattern="[0-9]{14,16}" class="form-control">
                    </div>
                </div>
            </div>


            <div class="text-right">
                <input required type="submit" value="Submit" class="btn btn-primary btn-lg">
            </div>
            </form>
        </div>
        <!-- /.card-body -->
    </div>

    @if (Session::has('message'))
        <script>
            $(document).ready(function() {
                Toast.fire({
                    icon: 'success',
                    title: 'User Created Successfully'
                })
            });
        </script>
    @endif

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')
    <style>


    </style>

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="heading col-sm-6">
                    <h1>Users</h1>
                </div>
                <div class="offset-sm-4  col-sm-2">
                    <h1 class="float-sm-right"><span
                        style="background-image: linear-gradient(121deg,black  1%, white 300%);
                        color: white;"
                            class="badge badge-pill">{{ $users->total() }}</span></h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card searcharea">
                    <div class="align-right">
                    </div>
                    <div class="card-header">
                        <br>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <form action="{{ route('users.index') }}" style="display: flex;">
                                    <div class="input-group border rounded-pill ">
                                        <input name="keyword" type="search" placeholder="Search"
                                            aria-describedby="button-addon3" class="form-control bg-none border-0">
                                        <div class="input-group-append border-0">
                                            <button id="button-addon3" type="submit" class="btn btn-link text-blue"><i
                                                    class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>

                                <a href="{{ route('users.create') }}"><button type="button"
                                        class="btn btn-primary rounded-pill rounded-bill">Add
                                        User</button></a>
                            </div>
                        </div>

                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap thb">
                            <thead class="table-dark">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Contact</th>
                                    {{-- <th>City</th> --}}
                                    <th>Address</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($users as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->first_name }} {{ $item->last_name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->contact }}</td>
                                    {{-- <td>{{ optional($item->area)->area_one->city->name }}</td> --}}
                                    <td>{{ $item->address }}</td>
                                    <td>

                                        <a href="{{ route('users.edit', $item->id) }}" class="float-left"><i
                                                class="fas fa-edit"></i></a>
                                        <form action="{{ route('users.destroy', $item->id) }}" method="POST">
                                            @method('delete') @csrf <button class="btn btn-link pt-0"><i
                                                    class="fas fa-trash-alt"></i></button> </form>
                                    </td>
                                </tr>
                            @empty
                                <p>No Data Found</p>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="align-right paginationstyle">
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->


                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    </div>

@endsection