routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('employees', 'EmployeeController');
Route::get('/', function () {
    return redirect()->route('employees.create');
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('profile', 'ProfileController');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- SweetAlert2 -->
    @yield('third_party_stylesheets')

    @stack('page_css')


<script>

    $(document).ready(function() {
                Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 3000
                });
    });
</script>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Main Header -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="{{asset('documents')}}/{{auth()->user()->profile_pic}}"
                         class="user-image img-circle elevation-2" alt="User Image">
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <!-- User image -->
                    <li class="user-header bg-primary">
                        <img src="{{asset('documents')}}/{{auth()->user()->profile_pic}}"
                             class="img-circle elevation-2"
                             alt="User Image">
                        <p>
                            {{ Auth::user()->name }}
                            <small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
                        </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <a href="{{route('profile.index')}}" class="btn btn-default btn-flat">Profile</a>
                        <a href="#" class="btn btn-default btn-flat float-right"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Sign out
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <!-- Left side column. contains the logo and sidebar -->
@include('layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content">
            @yield('content')
        </section>
    </div>

    <!-- Main Footer -->
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.0.5
        </div>
    </footer>
</div>

<script src="{{ asset('js/app.js') }}" defer></script>

@yield('third_party_scripts')

@stack('page_scripts')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>

resources/views/layouts/menu.blade.php
@if(auth()->user()->role_id==1)
<!-- need to remove -->
<style>
    [class*=sidebar-dark-] .nav-sidebar>.nav-item1.menu-open>.nav-link,
    [class*=sidebar-dark-] .nav-sidebar>.nav-item1>.nav-link:focus {
        background-color: #0b195261;
        color: #ffffff;
    }

</style>
    <li class="nav-item">
        <a href="{{ route('home') }}" class="nav-link @if(url()->current()==route('home')) active @endif">
            <i class="nav-icon fas fa-home"></i>
            <p>Home</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="{{ route('users.index') }}" class="nav-link @if(url()->current()==route('users.index') || url()->current()==route('users.create')) active @endif">
            <i class="nav-icon fas fa-users"></i>
            <p>Users</p>
        </a>
    </li>


    {{-- <li class="nav-item has-treeview  @if(url()->current()==route('users.index') || url()->current()==route('users.create')) menu-open @endif">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-users"></i>
            <p>
                Users
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('users.index') }}" class="nav-link">
                    <i class="far fa-circle nav-icon @if(url()->current()==route('users.index')) far fa-dot-circle  red @endif" ></i>
                    <p>List</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('users.create') }}" class="nav-link">
                    <i class="far fa-circle nav-icon @if(url()->current()==route('users.create')) far fa-dot-circle  red @endif"></i>
                    <p>Create</p>
                </a>
            </li>

        </ul>
    </li> --}}

    {{-- <li class="nav-item has-treeview  @if(url()->current()==route('employees.index') || url()->current()==route('employees.create')) menu-open @endif">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-users"></i>
            <p>
                Employees
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('employees.index') }}" class="nav-link">
                    <i class="far fa-circle nav-icon @if(url()->current()==route('employees.index')) far fa-dot-circle  red @endif" ></i>
                    <p>List</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('employees.create') }}" class="nav-link">
                    <i class="far fa-circle nav-icon @if(url()->current()==route('employees.create')) far fa-dot-circle  red @endif"></i>
                    <p>Create</p>
                </a>
            </li>

        </ul>
    </li> --}}

@endif

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('home') }}" class="brand-link">
        <img src="https://outcastsolutions.us/web/web/public/img/logo/SUUGXq.png"
             alt="AdminLTE Logo"
             class="brand-image elevation-3">
        <span class="brand-text font-weight-light">Admin Panel</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>

</aside>